Merge from HEAD
git-svn-id: http://rancid.shrubbery.net/rancid/svn/rancid@1969 137ac7c6-8f6c-0410-88de-aa6437057478

diff --git a/branches/dev-tex/rancid/bin/control_rancid.in b/branches/dev-tex/rancid/bin/control_rancid.in
--- a/branches/dev-tex/rancid/bin/control_rancid.in
+++ b/branches/dev-tex/rancid/bin/control_rancid.in
@@ -2,44 +2,64 @@
 ##
 ## $Id$
 ##
-## Copyright (C) 1997-2006 by Terrapin Communications, Inc.
+## @PACKAGE@ @VERSION@
+## Copyright (c) 1997-2008 by Terrapin Communications, Inc.
 ## All rights reserved.
 ##
-## This software may be freely copied, modified and redistributed
-## without fee for non-commerical purposes provided that this license
-## remains intact and unmodified with any RANCID distribution.
+## This code is derived from software contributed to and maintained by
+## Terrapin Communications, Inc. by Henry Kilmer, John Heasley, Andrew Partan,
+## Pete Whiting, Austin Schutz, and Andrew Fort.
 ##
-## There is no warranty or other guarantee of fitness of this software.
-## It is provided solely "as is".  The author(s) disclaim(s) all
-## responsibility and liability with respect to this software's usage
-## or its effect upon hardware, computer systems, other software, or
-## anything else.
+## Redistribution and use in source and binary forms, with or without
+## modification, are permitted provided that the following conditions
+## are met:
+## 1. Redistributions of source code must retain the above copyright
+##    notice, this list of conditions and the following disclaimer.
+## 2. Redistributions in binary form must reproduce the above copyright
+##    notice, this list of conditions and the following disclaimer in the
+##    documentation and/or other materials provided with the distribution.
+## 3. All advertising materials mentioning features or use of this software
+##    must display the following acknowledgement:
+##        This product includes software developed by Terrapin Communications,
+##        Inc. and its contributors for RANCID.
+## 4. Neither the name of Terrapin Communications, Inc. nor the names of its
+##    contributors may be used to endorse or promote products derived from
+##    this software without specific prior written permission.
+## 5. It is requested that non-binding fixes and modifications be contributed
+##    back to Terrapin Communications, Inc.
 ##
-## Except where noted otherwise, rancid was written by and is maintained by
-## Henry Kilmer, John Heasley, Andrew Partan, Pete Whiting, and Austin Schutz.
-##
-#
+## THIS SOFTWARE IS PROVIDED BY Terrapin Communications, INC. AND CONTRIBUTORS
+## ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
+## TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
+## PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COMPANY OR CONTRIBUTORS
+## BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
+## CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
+## SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
+## INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
+## CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
+## ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
+## POSSIBILITY OF SUCH DAMAGE.
+# 
 # control_rancid $GROUP
 #
 
 # print a usage message to stderr
 pr_usage() {
-    echo "usage: $0 [-r device_name] [-m mail rcpt] [group [group ...]]" >&2;
+    echo "usage: $0 [-V] [-r device_name] [-m mail rcpt] [group [group ...]]" >&2;
 }
 
 # command-line options
-# -r <device name>
+# -V print version string
 # -m <mail recipients>
+# -r <device name>
 alt_mailrcpt=0
 if [ $# -ge 1 ] ; then
 
     while [ 1 ] ; do
 	case $1 in
-	-r)
-	    shift
-	    # next arg is the device name
-	    device="$1"
-	    shift
+	-V)
+	    echo "@PACKAGE@ @VERSION@"
+	    exit 0
 	    ;;
 	-m)
 	    shift
@@ -50,6 +70,12 @@ if [ $# -ge 1 ] ; then
 	    else
 		mailrcpt="$mailrcpt,$1"
 	    fi
+	    shift
+	    ;;
+	-r)
+	    shift
+	    # next arg is the device name
+	    device="$1"
 	    shift
 	    ;;
 	--)
@@ -80,6 +106,9 @@ fi
 DIR=$BASEDIR/$GROUP
 TMP=${TMPDIR:=/tmp}/rancid.$GROUP.$$
 trap 'rm -fr $TMP;' 1 2 15
+
+# disable noclobber
+unset noclobber > /dev/null 2>&1
 
 # RCS system
 RCSSYS=${RCSSYS:=cvs};
@@ -350,7 +379,7 @@ cd $DIR/configs
 # tailored to the specific installation.
 echo ""
 echo "Trying to get all of the configs."
-par -q -n $PAR_COUNT -c "rancid-fe \{}" $devlistfile
+par -q -n $PAR_COUNT -c "rancid-fe {}" $devlistfile
 
 # This section will generate a list of missed routers
 # and try to grab them again.  It will run through
@@ -390,8 +419,8 @@ do
 done
 echo
 
-# Make sure that no empty configs are accepted.  Those that are non-empty
-# are renamed from device_name.new -> device_name.
+# Make sure that no empty/truncated configs are accepted.  The remainder are
+# renamed from device_name.new -> device_name.
 for router in `cat $devlistfile`
 do
     OFS=$IFS
@@ -404,9 +433,19 @@ do
     then
 	rm -f $router.new
     else
-	mv $router.new $router
-	if [ $? -ne 0 ]; then
-	    echo "Error: could not rename $router.new to $router"
+	lines=`awk '{if (/^([-*!;#]|\/\*)/) { next; } lines++; \
+		if (lines > 10) { print "1"; exit;}} \
+		END { if (lines < 10) {print "0";}}' $router.new`
+
+	if [ ! $lines ]
+	then
+	    rm -f $router.new
+	else
+	    mv $router.new $router
+	    if [ $? -ne 0 ]; then
+		echo "Error: could not rename $router.new to $router"
+		rm -f $router.new
+	    fi
 	fi
     fi
 done
